apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-server
  template:
    metadata:
      labels:
        app: image-server
    spec:
      containers:
      - name: image-server
        image: votre-compte/image-server:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: image-server
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP